# Generated by Django 4.2.16 on 2024-10-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemestoque',
            old_name='tamanho',
            new_name='modelo',
        ),
    ]
